version: "3.4"
services:
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    hostname: service-registry
    volumes:
     - ./consul/server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.10.0
    container_name: consul-client
    restart: always
    volumes:
     - ./consul/client.json:/consul/config/client.json:ro
    networks:
      - consul
    command: "agent"
    
  api-gateway:
    container_name: api-gateway
    depends_on:
        - consul-server
    networks:
      - consul
    build:
      context: .
      dockerfile: ApiGateway.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    ports: 
      - "7000:80" 
      
  admin-service:
    container_name: admin-service-api
    hostname: adminApi
    depends_on:
        - consul-server
    networks:
      - consul
    build:
      context: .
      dockerfile: Admin.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
     - ServiceConfig__ServiceAddress=http://adminApi
    ports: 
      - "7001:80"

  provider-service:
    container_name: provider-service-api
    hostname: providerApi
    depends_on:
        - consul-server
    networks:
      - consul
    build:
      context: .
      dockerfile: Provider.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ServiceConfig__ServiceDiscoveryAddress=http://service-registry:8500/
     - ServiceConfig__ServiceAddress=http://adminApi
    ports: 
      - "7002:80"
      
networks:
  consul:
    driver: bridge